services:
  database:
    image: 'postgres:16.0-alpine3.18'
    container_name: 'db_jstack'
    env_file:
      - ../.env.development
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
